# Generated by Django 4.1.7 on 2025-10-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=100)),
                ('Author_name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Publication_year', models.PositiveBigIntegerField()),
            ],
        ),
    ]
