# Generated by Django 4.1.7 on 2025-10-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secpubapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author_name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Book_name',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Publication_year',
            new_name='publication_year',
        ),
    ]
